version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ReactiveProperty
    versions:
    - 7.7.1
    - 7.8.0
    - 7.8.2
  - dependency-name: OpenTK
    versions:
    - 4.6.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: Xamarin.AndroidX.Lifecycle.LiveData
    versions:
    - 2.3.0
    - 2.3.0.1
  - dependency-name: Xamarin.Google.Android.Material
    versions:
    - 1.3.0
  - dependency-name: Xamarin.Essentials
    versions:
    - 1.6.1
